--appDatasource创建字典表
CREATE TABLE "SYS_DICT" 
   ("ID" VARCHAR2(64) NOT NULL ENABLE, 
	"VALUE" VARCHAR2(100) NOT NULL ENABLE, 
	"LABEL" VARCHAR2(100) NOT NULL ENABLE, 
	"TYPE" VARCHAR2(100) NOT NULL ENABLE, 
	"DESCRIPTION" NVARCHAR2(100) NOT NULL ENABLE, 
	"SORT" NUMBER(10,0) NOT NULL ENABLE, 
	"PARENT_ID" VARCHAR2(64) DEFAULT '0', 
	"CREATE_BY" VARCHAR2(64) NOT NULL ENABLE, 
	"CREATE_DATE" TIMESTAMP (6) NOT NULL ENABLE, 
	"UPDATE_BY" VARCHAR2(64) NOT NULL ENABLE, 
	"UPDATE_DATE" TIMESTAMP (6) NOT NULL ENABLE, 
	"REMARKS" NVARCHAR2(255), 
	"DEL_FLAG" CHAR(1) DEFAULT '0' NOT NULL ENABLE, 
	"GROUPS" VARCHAR2(255), 
	 PRIMARY KEY ("ID")
   );