package pojo;

import java.io.Serializable;

public class GrsnapshotLogWithBLOBs extends GrsnapshotLog implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SWORDRISK.GRSNAPSHOT_LOG.PARAMS
     *
     * @mbggenerated Fri Nov 03 11:40:49 CST 2017
     */
    private String params;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SWORDRISK.GRSNAPSHOT_LOG.HTML
     *
     * @mbggenerated Fri Nov 03 11:40:49 CST 2017
     */
    private String html;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SWORDRISK.GRSNAPSHOT_LOG.PAGEVALUE
     *
     * @mbggenerated Fri Nov 03 11:40:49 CST 2017
     */
    private String pagevalue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SWORDRISK.GRSNAPSHOT_LOG
     *
     * @mbggenerated Fri Nov 03 11:40:49 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWORDRISK.GRSNAPSHOT_LOG.PARAMS
     *
     * @return the value of SWORDRISK.GRSNAPSHOT_LOG.PARAMS
     *
     * @mbggenerated Fri Nov 03 11:40:49 CST 2017
     */
    public String getParams() {
        return params;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWORDRISK.GRSNAPSHOT_LOG.PARAMS
     *
     * @param params the value for SWORDRISK.GRSNAPSHOT_LOG.PARAMS
     *
     * @mbggenerated Fri Nov 03 11:40:49 CST 2017
     */
    public void setParams(String params) {
        this.params = params == null ? null : params.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWORDRISK.GRSNAPSHOT_LOG.HTML
     *
     * @return the value of SWORDRISK.GRSNAPSHOT_LOG.HTML
     *
     * @mbggenerated Fri Nov 03 11:40:49 CST 2017
     */
    public String getHtml() {
        return html;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWORDRISK.GRSNAPSHOT_LOG.HTML
     *
     * @param html the value for SWORDRISK.GRSNAPSHOT_LOG.HTML
     *
     * @mbggenerated Fri Nov 03 11:40:49 CST 2017
     */
    public void setHtml(String html) {
        this.html = html == null ? null : html.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWORDRISK.GRSNAPSHOT_LOG.PAGEVALUE
     *
     * @return the value of SWORDRISK.GRSNAPSHOT_LOG.PAGEVALUE
     *
     * @mbggenerated Fri Nov 03 11:40:49 CST 2017
     */
    public String getPagevalue() {
        return pagevalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWORDRISK.GRSNAPSHOT_LOG.PAGEVALUE
     *
     * @param pagevalue the value for SWORDRISK.GRSNAPSHOT_LOG.PAGEVALUE
     *
     * @mbggenerated Fri Nov 03 11:40:49 CST 2017
     */
    public void setPagevalue(String pagevalue) {
        this.pagevalue = pagevalue == null ? null : pagevalue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWORDRISK.GRSNAPSHOT_LOG
     *
     * @mbggenerated Fri Nov 03 11:40:49 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", params=").append(params);
        sb.append(", html=").append(html);
        sb.append(", pagevalue=").append(pagevalue);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}