package pojo;

import java.io.Serializable;
import java.util.Date;

import annotation.Table;
import annotation.TableColumn;

@Table(tableName="grsnapshot_log",orderBy="create_date")
public class GrsnapshotLog implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SWORDRISK.GRSNAPSHOT_LOG.ID
     *
     * @mbggenerated Fri Nov 03 11:40:49 CST 2017
     */
	@TableColumn(dbColumn="ID")
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SWORDRISK.GRSNAPSHOT_LOG.TITLE
     *
     * @mbggenerated Fri Nov 03 11:40:49 CST 2017
     */
	@TableColumn(dbColumn="title",excelHeader="标题")
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SWORDRISK.GRSNAPSHOT_LOG.CREATE_BY
     *
     * @mbggenerated Fri Nov 03 11:40:49 CST 2017
     */
	@TableColumn(dbColumn="create_by",excelHeader="创建者")
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SWORDRISK.GRSNAPSHOT_LOG.CREATE_DATE
     *
     * @mbggenerated Fri Nov 03 11:40:49 CST 2017
     */
    private Date createDate;
    //类型转换。 db中to_char把类型转换成了String,需要用string属性接收。
    @TableColumn(dbColumn="create_date",dbFunc="to_char(create_date,'yyyy-mm-dd hh:mi:ss')",excelHeader="操作时间")
    private String createDateStr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SWORDRISK.GRSNAPSHOT_LOG.REMOTE_ADDR
     *
     * @mbggenerated Fri Nov 03 11:40:49 CST 2017
     */
    @TableColumn(dbColumn="remote_addr",excelHeader="操作者IP")
    private String remoteAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SWORDRISK.GRSNAPSHOT_LOG.REQUEST_URI
     *
     * @mbggenerated Fri Nov 03 11:40:49 CST 2017
     */
    @TableColumn(dbColumn="request_uri",excelHeader="URI")
    private String requestUri;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SWORDRISK.GRSNAPSHOT_LOG
     *
     * @mbggenerated Fri Nov 03 11:40:49 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWORDRISK.GRSNAPSHOT_LOG.ID
     *
     * @return the value of SWORDRISK.GRSNAPSHOT_LOG.ID
     *
     * @mbggenerated Fri Nov 03 11:40:49 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWORDRISK.GRSNAPSHOT_LOG.ID
     *
     * @param id the value for SWORDRISK.GRSNAPSHOT_LOG.ID
     *
     * @mbggenerated Fri Nov 03 11:40:49 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWORDRISK.GRSNAPSHOT_LOG.TITLE
     *
     * @return the value of SWORDRISK.GRSNAPSHOT_LOG.TITLE
     *
     * @mbggenerated Fri Nov 03 11:40:49 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWORDRISK.GRSNAPSHOT_LOG.TITLE
     *
     * @param title the value for SWORDRISK.GRSNAPSHOT_LOG.TITLE
     *
     * @mbggenerated Fri Nov 03 11:40:49 CST 2017
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWORDRISK.GRSNAPSHOT_LOG.CREATE_BY
     *
     * @return the value of SWORDRISK.GRSNAPSHOT_LOG.CREATE_BY
     *
     * @mbggenerated Fri Nov 03 11:40:49 CST 2017
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWORDRISK.GRSNAPSHOT_LOG.CREATE_BY
     *
     * @param createBy the value for SWORDRISK.GRSNAPSHOT_LOG.CREATE_BY
     *
     * @mbggenerated Fri Nov 03 11:40:49 CST 2017
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWORDRISK.GRSNAPSHOT_LOG.CREATE_DATE
     *
     * @return the value of SWORDRISK.GRSNAPSHOT_LOG.CREATE_DATE
     *
     * @mbggenerated Fri Nov 03 11:40:49 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWORDRISK.GRSNAPSHOT_LOG.CREATE_DATE
     *
     * @param createDate the value for SWORDRISK.GRSNAPSHOT_LOG.CREATE_DATE
     *
     * @mbggenerated Fri Nov 03 11:40:49 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWORDRISK.GRSNAPSHOT_LOG.REMOTE_ADDR
     *
     * @return the value of SWORDRISK.GRSNAPSHOT_LOG.REMOTE_ADDR
     *
     * @mbggenerated Fri Nov 03 11:40:49 CST 2017
     */
    public String getRemoteAddr() {
        return remoteAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWORDRISK.GRSNAPSHOT_LOG.REMOTE_ADDR
     *
     * @param remoteAddr the value for SWORDRISK.GRSNAPSHOT_LOG.REMOTE_ADDR
     *
     * @mbggenerated Fri Nov 03 11:40:49 CST 2017
     */
    public void setRemoteAddr(String remoteAddr) {
        this.remoteAddr = remoteAddr == null ? null : remoteAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SWORDRISK.GRSNAPSHOT_LOG.REQUEST_URI
     *
     * @return the value of SWORDRISK.GRSNAPSHOT_LOG.REQUEST_URI
     *
     * @mbggenerated Fri Nov 03 11:40:49 CST 2017
     */
    public String getRequestUri() {
        return requestUri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SWORDRISK.GRSNAPSHOT_LOG.REQUEST_URI
     *
     * @param requestUri the value for SWORDRISK.GRSNAPSHOT_LOG.REQUEST_URI
     *
     * @mbggenerated Fri Nov 03 11:40:49 CST 2017
     */
    public void setRequestUri(String requestUri) {
        this.requestUri = requestUri == null ? null : requestUri.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWORDRISK.GRSNAPSHOT_LOG
     *
     * @mbggenerated Fri Nov 03 11:40:49 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", title=").append(title);
        sb.append(", createBy=").append(createBy);
        sb.append(", createDate=").append(createDate);
        sb.append(", remoteAddr=").append(remoteAddr);
        sb.append(", requestUri=").append(requestUri);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

	public String getCreateDateStr() {
		return createDateStr;
	}

	public void setCreateDateStr(String createDateStr) {
		this.createDateStr = createDateStr;
	}
}