package pojo;

import java.io.Serializable;

import annotation.Table;
import annotation.TableColumn;

@Table(tableName = "sysdict",expFileName="系统数据字典",orderBy="update_time",order="desc")
public class Sysdict implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysdict.dict_id
     *
     * @mbggenerated Tue Feb 27 16:25:22 CST 2018
     */
	@TableColumn(dbColumn="dict_id")
    private String dictId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysdict.dict_value
     *
     * @mbggenerated Tue Feb 27 16:25:22 CST 2018
     */
	@TableColumn(dbColumn="dict_value",excelHeader="字典值")
    private String dictValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysdict.dict_label
     *
     * @mbggenerated Tue Feb 27 16:25:22 CST 2018
     */
	@TableColumn(dbColumn="dict_label",excelHeader="字典内容")
    private String dictLabel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysdict.dict_type
     *
     * @mbggenerated Tue Feb 27 16:25:22 CST 2018
     */
	@TableColumn(dbColumn="dict_type",excelHeader="字典类型 ")
    private String dictType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysdict.dict_type_desc
     *
     * @mbggenerated Tue Feb 27 16:25:22 CST 2018
     */
	@TableColumn(dbColumn="dict_type_desc",excelHeader="字典类型描述")
    private String dictTypeDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysdict.update_by
     *
     * @mbggenerated Tue Feb 27 16:25:22 CST 2018
     */
	@TableColumn(dbColumn="update_by")
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysdict.update_time
     *
     * @mbggenerated Tue Feb 27 16:25:22 CST 2018
     */
	@TableColumn(dbColumn="update_time",dbFunc="date_format(update_time,'%y-%m-%d %T')")
    private String updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sysdict
     *
     * @mbggenerated Tue Feb 27 16:25:22 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysdict.dict_id
     *
     * @return the value of sysdict.dict_id
     *
     * @mbggenerated Tue Feb 27 16:25:22 CST 2018
     */
    public String getDictId() {
        return dictId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysdict.dict_id
     *
     * @param dictId the value for sysdict.dict_id
     *
     * @mbggenerated Tue Feb 27 16:25:22 CST 2018
     */
    public void setDictId(String dictId) {
        this.dictId = dictId == null ? null : dictId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysdict.dict_value
     *
     * @return the value of sysdict.dict_value
     *
     * @mbggenerated Tue Feb 27 16:25:22 CST 2018
     */
    public String getDictValue() {
        return dictValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysdict.dict_value
     *
     * @param dictValue the value for sysdict.dict_value
     *
     * @mbggenerated Tue Feb 27 16:25:22 CST 2018
     */
    public void setDictValue(String dictValue) {
        this.dictValue = dictValue == null ? null : dictValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysdict.dict_label
     *
     * @return the value of sysdict.dict_label
     *
     * @mbggenerated Tue Feb 27 16:25:22 CST 2018
     */
    public String getDictLabel() {
        return dictLabel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysdict.dict_label
     *
     * @param dictLabel the value for sysdict.dict_label
     *
     * @mbggenerated Tue Feb 27 16:25:22 CST 2018
     */
    public void setDictLabel(String dictLabel) {
        this.dictLabel = dictLabel == null ? null : dictLabel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysdict.dict_type
     *
     * @return the value of sysdict.dict_type
     *
     * @mbggenerated Tue Feb 27 16:25:22 CST 2018
     */
    public String getDictType() {
        return dictType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysdict.dict_type
     *
     * @param dictType the value for sysdict.dict_type
     *
     * @mbggenerated Tue Feb 27 16:25:22 CST 2018
     */
    public void setDictType(String dictType) {
        this.dictType = dictType == null ? null : dictType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysdict.dict_type_desc
     *
     * @return the value of sysdict.dict_type_desc
     *
     * @mbggenerated Tue Feb 27 16:25:22 CST 2018
     */
    public String getDictTypeDesc() {
        return dictTypeDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysdict.dict_type_desc
     *
     * @param dictTypeDesc the value for sysdict.dict_type_desc
     *
     * @mbggenerated Tue Feb 27 16:25:22 CST 2018
     */
    public void setDictTypeDesc(String dictTypeDesc) {
        this.dictTypeDesc = dictTypeDesc == null ? null : dictTypeDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysdict.update_by
     *
     * @return the value of sysdict.update_by
     *
     * @mbggenerated Tue Feb 27 16:25:22 CST 2018
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysdict.update_by
     *
     * @param updateBy the value for sysdict.update_by
     *
     * @mbggenerated Tue Feb 27 16:25:22 CST 2018
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysdict.update_time
     *
     * @return the value of sysdict.update_time
     *
     * @mbggenerated Tue Feb 27 16:25:22 CST 2018
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysdict.update_time
     *
     * @param updateTime the value for sysdict.update_time
     *
     * @mbggenerated Tue Feb 27 16:25:22 CST 2018
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysdict
     *
     * @mbggenerated Tue Feb 27 16:25:22 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", dictId=").append(dictId);
        sb.append(", dictValue=").append(dictValue);
        sb.append(", dictLabel=").append(dictLabel);
        sb.append(", dictType=").append(dictType);
        sb.append(", dictTypeDesc=").append(dictTypeDesc);
        sb.append(", updateBy=").append(updateBy);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}