--APPDataSource中创建快照记录表
CREATE TABLE "GRSNAPSHOT_LOG" 
   ("ID" VARCHAR2(64) NOT NULL ENABLE, 
	"TITLE" VARCHAR2(500), 
	"CREATE_BY" VARCHAR2(64), 
	"CREATE_DATE" TIMESTAMP (6), 
	"REMOTE_ADDR" VARCHAR2(255), 
	"REQUEST_URI" VARCHAR2(255), 
	"PARAMS" CLOB, 
	"HTML" CLOB, 
	"PAGEVALUE" CLOB
   )