CREATE TABLE GRSNAPSHOT_LOG
   (ID VARCHAR(64) NOT NULL PRIMARY KEY, 
	TITLE VARCHAR(500), 
	CREATE_BY VARCHAR(64), 
	CREATE_DATE TIMESTAMP (6), 
	REMOTE_ADDR VARCHAR(255), 
	REQUEST_URI VARCHAR(255), 
	PARAMS MEDIUMTEXT, 
	HTML MEDIUMTEXT, 
	PAGEVALUE MEDIUMTEXT
   )