package com.genService.mapper;

import org.apache.ibatis.annotations.Param;
import pojo.GrsnapshotLog;
import pojo.GrsnapshotLogExample;
import pojo.GrsnapshotLogWithBLOBs;

import java.util.List;

public interface GrsnapshotLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWORDRISK.GRSNAPSHOT_LOG
     *
     * @mbggenerated Fri Nov 03 11:40:49 CST 2017
     */
    int countByExample(GrsnapshotLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWORDRISK.GRSNAPSHOT_LOG
     *
     * @mbggenerated Fri Nov 03 11:40:49 CST 2017
     */
    int deleteByExample(GrsnapshotLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWORDRISK.GRSNAPSHOT_LOG
     *
     * @mbggenerated Fri Nov 03 11:40:49 CST 2017
     */
    int insert(GrsnapshotLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWORDRISK.GRSNAPSHOT_LOG
     *
     * @mbggenerated Fri Nov 03 11:40:49 CST 2017
     */
    int insertSelective(GrsnapshotLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWORDRISK.GRSNAPSHOT_LOG
     *
     * @mbggenerated Fri Nov 03 11:40:49 CST 2017
     */
    List<GrsnapshotLogWithBLOBs> selectByExampleWithBLOBs(GrsnapshotLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWORDRISK.GRSNAPSHOT_LOG
     *
     * @mbggenerated Fri Nov 03 11:40:49 CST 2017
     */
    List<GrsnapshotLog> selectByExample(GrsnapshotLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWORDRISK.GRSNAPSHOT_LOG
     *
     * @mbggenerated Fri Nov 03 11:40:49 CST 2017
     */
    int updateByExampleSelective(@Param("record") GrsnapshotLogWithBLOBs record, @Param("example") GrsnapshotLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWORDRISK.GRSNAPSHOT_LOG
     *
     * @mbggenerated Fri Nov 03 11:40:49 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") GrsnapshotLogWithBLOBs record, @Param("example") GrsnapshotLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SWORDRISK.GRSNAPSHOT_LOG
     *
     * @mbggenerated Fri Nov 03 11:40:49 CST 2017
     */
    int updateByExample(@Param("record") GrsnapshotLog record, @Param("example") GrsnapshotLogExample example);
}